<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Applay' => 'Meklēt',
  'Date from-to' => '',
  'Last 30 Days' => '',
  'Last 7 Days' => '',
  'Cancel' => 'Atcelt',
  'Custom range' => 'Cits diapozons',
  'From' => 'no',
  'Last Month' => 'Iepr. mēnesis',
  'Last week' => 'Iepr. nedēļa',
  'This Month' => 'Šis mēnesis',
  'This Year' => 'Šis gads',
  'This week' => 'Šī nedēļa',
  'To' => 'līdz',
  'Today' => 'Šodiena',
  'Yesterday' => 'Vakardiena',
);
